// Generated by Copilot
import { test, expect } from '@playwright/test';

test('Search for Garfield and verify it appears in the results', async ({ page }) => {
  // Navigate to the movie database website
  await page.goto('https://www.themoviedb.org/');
  
  // Verify that the page loaded correctly
  await expect(page).toHaveTitle(/The Movie Database/);
  
  // Search for Garfield
  const searchInput = await page.waitForSelector('input[name="query"], .search input');
  await searchInput.fill('Garfield');
  
  // Submit the search
  await searchInput.press('Enter');
  
  // Wait for the search results to load
  await page.waitForLoadState('networkidle');
  
  // Verify that we're on the search results page
  await expect(page).toHaveURL(/.*\/search.*/);
  
  // Verify that Garfield appears in the search results
  // First, make sure we're on the results page by checking for the search results header
  await expect(page.locator('.search_results h3:has-text("Search Results")')).toBeVisible();
  
  // Look for Garfield in the results using the card title selector (most reliable)
  const garfieldResults = page.locator('.card .details .title h2:has-text("Garfield")');
  await expect(garfieldResults.first()).toBeVisible();
  
  // Count how many Garfield results are found (for logging purposes)
  const count = await garfieldResults.count();
  console.log(`Found ${count} results containing Garfield`);
  
  // Take a screenshot of the search results for reference
  await page.screenshot({ path: './test-results/garfield-search-results.png' });
});
